export const USER_AUTHENTICATE = 'USER_AUTHENTICATE';
export const USER_AUTHENTICATE_ERROR = 'USER_AUTHENTICATE_ERROR';
export const USER_AUTHENTICATE_SUCCESS = 'USER_AUTHENTICATE_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';

export const NOTIFICATION_NEW = 'NOTIFICATION_NEW';
